stages:
- name: Build and Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./stripes-deploy/Dockerfile
      buildContext: ./
      tag: celticmask/platform-complete:folijet-latest
      pushRemote: true
      registry: index.docker.io
    envFrom:
      - sourceName: tenant-config
        sourceKey: TENANT_ID
      - sourceName: tenant-config
        sourceKey: OKAPI_URL
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_BUILD_ARGS_FROM_ENV: OKAPI_URL, TENANT_ID
    when:
      branch: {}
      event: {}
  when:
    branch: {}
    event: {}
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-mf42h:folijet-helmcharts-platform-complete
      version: 0.1.1
      answers:
        image.repository: celticmask/platform-complete
        image.tag: folijet-latest
      targetNamespace: folijet
      name: mod-pubsub
timeout: 60
